### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rfviolato** [rfviolato/boilerplate#1]
- [ ] Making old config work with webpack 2
- [ ] Devserver file & getting what's interesting from other boilerplate projects (**DONT FORGET TO REMOVER WEBPACK-DEV-SERVER FROM DEPS ONCE THIS IS DONE**)
- [ ] Wire-up all front-end project deps (Redux, router...)
